# This file is used by the Thunderstore CLI to build and publish your mod to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "hazre"
name = "SettingsScroll"
# versionNumber = "1.0.0" # Uncomment this if publishing via manual tcli! Change this to your mod's version, must be in semantic versioning format (e.g. 1.0.0, 2.1.3, 0.1.0-alpha.1)
description = "Fixes settings panel category scrolling so you can scroll through all categories without them being cut off"
websiteUrl = "https://github.com/hazre/SettingsScroll"
containsNsfwContent = false

# List any dependencies your mod has here, in the format "namespace-modname" = "version-constraint"
[package.dependencies]
ResoniteModding-BepisLoader = "1.6.0"
ResoniteModding-BepisLocaleLoader = "1.2.0"
MonoDetour-MonoDetour_BepInEx_6 = "0.7.10"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

# Copy the compiled DLL to the plugins folder in the mod package
[[build.copy]]
source = "./SettingsScroll/bin/Release/SettingsScroll.dll"
target = "plugins/SettingsScroll/"

# Include the PDB file for better debugging support
[[build.copy]]
source = "./SettingsScroll/bin/Release/SettingsScroll.pdb"
target = "plugins/SettingsScroll/"

# Include locale files
[[build.copy]]
source = "./SettingsScroll/Locale"
target = "plugins/SettingsScroll/Locale"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

# Uncomment the following line to include LICENSE file in your mod package, if you have one.
[[build.copy]]
source = "./LICENSE"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = ["mods", "dashboard", "bugworkaround"]
